version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 22.x
    commands:
      - echo "Ensuring latest main branch is checked out..."
      - git fetch origin main
      - git checkout main
      - git reset --hard origin/main
      - echo "Current commit:"
      - git log -1 --oneline

      - echo "Installing dependencies..."
      - corepack enable
      - pnpm install

  build:
    commands:
      - echo "Deploying to ${STAGE}..."
      - pnpm run deploy

  post_build:
    commands:
      - echo "Deployment completed successfully for ${STAGE}"